# Generated by Django 4.1 on 2022-08-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="work_at",
            field=models.CharField(default=None, max_length=155),
            preserve_default=False,
        ),
    ]
