# Generated by Django 4.1 on 2022-08-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="user",
            new_name="followers_users",
        ),
        migrations.RenameField(
            model_name="follower",
            old_name="profile",
            new_name="following_users",
        ),
    ]
