# Generated by Django 4.1 on 2022-08-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_rename_user_follower_followers_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
